### ISSUE TITLE
Classname[] results in validation error

### ISSUE THREAD

**Issue by michaeldoehler** [techdivision/php-by-contract#3]
Shorthand for Array, e.g. 

/**
 * all available commands
 * @var Command[]
 */
private $commands;

..results in Validation error, because Comand[] cannot be instantiates.

I fixed it very low-level in InstanceAssertion.php ( Line 70 ):

$this->class = str_replace('[]', '', $this->class);

I know its a quick and dirty fix...

Please come up with a solution if i completely wrong, but i think this short-hand is common or?

**Comment by wick-ed** [comment]
Hi @michaeldoehler ,

sorry for the enormously long wait, the issue got swallowed in the wake of the deprecation of this repository. :(
The requested functionality is implemented in the latest version of [appserver-io/doppelgaenger](https://github.com/appserver-io/doppelgaenger).
Doppelgaenger has also been part of the [appserver](http://appserver.io/) releases for a while.
Your feature will therefor be included into coming appserver.io releases.

Regards,
Bernhard
